apiVersion: v1 
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
  - targetPort: 6789
    port: 6789
    
  selector:
    name: postgres-app
    app: demo-voting-app


