apiVersion: v1 
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 5432
    
  selector:
    name: redis-app
    app: demo-voting-app


