apiVersion: apps/v1
kind: Deployment
metadata: 
  name: voting-deploy
  labels:
    name: voting-deploy
    app: demo-voting-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app
      app: demo-voting-app
  template:
    metadata: 
      name: voting-app
      labels:
        name: voting-app
        app: demo-voting-app
    spec:
      containers: 
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
  
